# Generated by Django 2.2.28 on 2022-07-16 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.IntegerField(default=1, help_text='Введите количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
