# Generated by Django 2.2.28 on 2022-07-16 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220716_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(blank=True, default=1, help_text='Введите количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.IntegerField(blank=True, default=1, help_text='Введите количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
